name: Build and Upload Jar

on:
  push:
    branches:
      - folia-patches
  pull_request:
    branches:
      - folia-patches

permissions: write-all

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to script
        run: bash -c "chmod +x script.sh"

      - name: Update upstream and apply patches
        shell: bash
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Action Github"
          ./script.sh updateUpstream
          ./script.sh applyPatches

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build
        shell: bash
        run: |
          cd Essentials-Patchs
          ./gradlew build --stacktrace -x test -x checkstyleMain --refresh-dependencies

      - name: Archive plugin jars on GitHub
        uses: actions/upload-artifact@v4
        with:
          name: EssentialsX plugin jars
          path: Essentials-Patchs/jars/

      - name: Create Release
        if: github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.tag }}
          name: ${{ env.project_id_b }} ${{ env.mcversion }} - ${{ env.commit_id }}
          body: |
            This release is automatically compiled by GitHub Actions
            ### Commit Message
            ${{ env.commit_msg }}
          artifacts: ${{ env.jar_dir }}
          generateReleaseNotes: true
          prerelease: ${{ env.pre }}
          makeLatest: ${{ env.make_latest }}
          token: ${{ secrets.GITHUB_TOKEN }}